- name: Demo on roles
  ansible.builtin.debug:
    msg: Hello from roles

- name: variable from role
  ansible.builtin.debug:
    msg: URL is - {{ URL }}

- name: variable from play
  ansible.builtin.debug:
    msg: url play is - {{ URL_PLAY }}
